default:
  image: node:20
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  before_script:
    - npm ci

stages:
  - lint
  - typecheck
  - build

lint:
  stage: lint
  script:
    - npm run lint
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == "main"

typecheck:
  stage: typecheck
  script:
    - npm run typecheck
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == "main"

build:
  stage: build
  script:
    - |
      echo "VITE_YANDEX_MAPS_KEY=${VITE_YANDEX_MAPS_KEY}" >> .env
      echo "VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}" >> .env
      echo "VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}" >> .env
      echo "VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}" >> .env
      echo "VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}" >> .env
      echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}" >> .env
      echo "VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}" >> .env
    - npm run build
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - dist/
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == "main"
